name: Deploy to EC2 Test

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Deploy to EC2 Test
          run: |
             echo "Installing Node.js..."
             if ! command -v nvm &> /dev/null; then
             curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
             export NVM_DIR="$HOME/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
             fi
             nvm install node

             echo "Installing PM2..."
             if ! command -v pm2 &> /dev/null; then
             npm install -g pm2
             fi

             REPO_URL="https://github.com/oaadonsgithub/node-countries.git"
             BRANCH="main"
             REPO_DIR="$HOME/node-countries"

             if [ -d "$REPO_DIR/.git" ]; then
             cd "$REPO_DIR"
             git pull origin "$BRANCH"
             else
             git clone "$REPO_URL" "$REPO_DIR"
             cd "$REPO_DIR"
             fi

             cd "$REPO_DIR"
             npm install

             cd ~/node-countries
             git pull origin main
             npm install

             echo "Starting/restarting application..."
             pm2 restart server.js || pm2 start server.js
             
      
