name: Deploy to EC2 Test

on:
  push:
    branches: [ main ]

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Deploy to EC2 Test
          run: |
             git pull origin main
             nvm install node
             echo "Installing PM2..."
             if ! command -v pm2 &> /dev/null; then
             npm install -g pm2
             fi
             npm install
             echo "Starting/restarting application..."
             pm2 restart server.js || pm2 start server.js
             
      
